spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://token-app-user:YLmFK4HXE5yqzwsy@cluster0.ttii4dh.mongodb.net/product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka